[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/crow-intelligence/chronowords/blob/main/examples/presidential_speeches.ipynb)

In [1]:
# From a clone of the repository, run this notebook in the project environment
# instead of installing from PyPI:
#     uv sync --group examples && uv run jupyter lab examples/
# Elsewhere (e.g. Colab), install a release that includes the Rust core:
# %pip install "chronowords>=0.4"

# Load presidential speeches

In [2]:
import json


with open("../data/corpus/speeches_lemmatized.json", encoding="utf-8") as f:
    speeches = json.load(f)

# Preprocessing the corpus

In [3]:
from collections import defaultdict
from pathlib import Path


# Per-period text files are rebuildable, so they go to the gitignored
# data/derived/ directory rather than next to the bundled corpus.
OUT_DIR = Path("../data/derived/presidential")
OUT_DIR.mkdir(parents=True, exist_ok=True)


def group_speeches_by_quarter_century(speeches_list):
    """Group speeches into quarter centuries and create text files.

    Args:
        speeches_list: List of dictionaries containing speech data

    Returns:
        Dictionary with quarter century ranges as keys and filenames as values

    """
    # Group speeches by quarter century
    quarter_groups = defaultdict(list)

    for speech in speeches_list:
        year = int(speech["date"][:4])  # Get year from date
        # Calculate quarter century (1800-1824, 1825-1849, etc.)
        quarter_start = year - (year % 25)
        quarter_end = quarter_start + 24
        quarter_key = f"{quarter_start}-{quarter_end}"

        quarter_groups[quarter_key].append(speech)

    # Create text files for each quarter century
    file_paths = {}
    for quarter, speeches in quarter_groups.items():
        # Sort speeches by date
        speeches.sort(key=lambda x: x["date"])

        # Create lemmatized version
        lemma_text = "\n".join(s["lemmatized"] for s in speeches)
        lemma_filename = OUT_DIR / f"speeches_{quarter}_lemmatized.txt"
        with open(lemma_filename, "w", encoding="utf-8") as f:
            f.write(lemma_text)

        # Create transcript version
        transcript_text = "\n".join(s["transcript"] for s in speeches)
        transcript_filename = OUT_DIR / f"speeches_{quarter}_transcript.txt"
        with open(transcript_filename, "w", encoding="utf-8") as f:
            f.write(transcript_text)

        file_paths[quarter] = {
            "lemmatized": lemma_filename,
            "transcript": transcript_filename,
            "count": len(speeches),
        }

    # Print summary
    print("Quarter Century Statistics:")
    for quarter, info in sorted(file_paths.items()):
        print(f"{quarter}: {info['count']} speeches")

    return file_paths


file_paths = group_speeches_by_quarter_century(speeches)

Quarter Century Statistics:
1775-1799: 28 speeches
1800-1824: 59 speeches
1825-1849: 90 speeches
1850-1874: 108 speeches
1875-1899: 99 speeches
1900-1924: 91 speeches
1925-1949: 103 speeches
1950-1974: 165 speeches
1975-1999: 150 speeches
2000-2024: 164 speeches
2025-2049: 1 speeches

# Building language models

In [4]:
from pathlib import Path

from chronowords.algebra.svd import SVDAlgebra


def create_embeddings_for_periods(file_paths, use_lemmatized=True):
    """Create word embeddings for each quarter-century period.

    Args:
        file_paths: Dictionary from group_speeches_by_quarter_century
        use_lemmatized: Whether to use lemmatized or transcript texts

    Returns:
        Dictionary of {period: SVDAlgebra model}

    """
    models = {}

    for period, info in sorted(file_paths.items()):
        print(f"\nProcessing period {period}")

        # Choose which text version to use
        filename = info["lemmatized" if use_lemmatized else "transcript"]

        model = SVDAlgebra(
            n_components=100,  # Smaller dimension for historical texts
            window_size=5,
            min_word_length=3,
            # A quarter-century of speeches is 0.1-4 MB of text; the default
            # min_count=100 suits gigabyte corpora.
            min_count=20,
            # Transcripts are raw text: segment into words, drop punctuation
            # and lowercase. Lemmatised text is already split and lowercased.
            tokenizer="whitespace" if use_lemmatized else "unicode",
            lowercase=True,
        )

        try:
            # A Path is read directly by the compiled core
            model.train(Path(filename))
        except ValueError as e:
            # e.g. the 2025-2049 slice is too small for min_count=20
            print(f"Skipping {period}: {e}")
            continue

        rec = model.training_record
        print(
            f"{rec['word_total']:,} tokens, vocabulary {rec['vocab_size']:,}, "
            f"PPMI entries {rec['ppmi_nnz']:,}"
        )
        # Procrustes alignment needs every period in the same 100 dimensions;
        # a slice with fewer than 101 vocabulary words cannot provide them.
        if rec["n_components_used"] < model.n_components:
            print(f"Skipping {period}: too little text for {model.n_components} dimensions")
            continue
        models[period] = model

    return models


# Create models for both lemmatized and transcript versions
print("Creating models for lemmatized texts...")
lemma_models = create_embeddings_for_periods(file_paths, use_lemmatized=True)

print("\nCreating models for transcript texts...")
transcript_models = create_embeddings_for_periods(file_paths, use_lemmatized=False)

# Save models for later use (models/ is gitignored)
for period, model in lemma_models.items():
    save_path = Path(f"../models/lemmatized/{period}")
    save_path.mkdir(parents=True, exist_ok=True)
    model.save_model(save_path)

for period, model in transcript_models.items():
    save_path = Path(f"../models/transcript/{period}")
    save_path.mkdir(parents=True, exist_ok=True)
    model.save_model(save_path)

Creating models for lemmatized texts...

Processing period 1775-1799

33,875 tokens, vocabulary 259, PPMI entries 6,512

Processing period 1800-1824
97,700 tokens, vocabulary 775, PPMI entries 33,639

Processing period 1825-1849

341,041 tokens, vocabulary 1,868, PPMI entries 127,213

Processing period 1850-1874

351,722 tokens, vocabulary 1,949, PPMI entries 146,454

Processing period 1875-1899

390,323 tokens, vocabulary 2,134, PPMI entries 170,094

Processing period 1900-1924

360,878 tokens, vocabulary 2,025, PPMI entries 147,113

Processing period 1925-1949

235,563 tokens, vocabulary 1,474, PPMI entries 90,903

Processing period 1950-1974

437,734 tokens, vocabulary 2,046, PPMI entries 170,015

Processing period 1975-1999

454,187 tokens, vocabulary 2,073, PPMI entries 165,081

Processing period 2000-2024

508,620 tokens, vocabulary 2,173, PPMI entries 174,855

Processing period 2025-2049
1,858 tokens, vocabulary 6, PPMI entries 13
Skipping 2025-2049: too little text for 100 dimensions

Creating models for transcript texts...

Processing period 1775-1799

34,533 tokens, vocabulary 236, PPMI entries 5,649

Processing period 1800-1824
99,820 tokens, vocabulary 758, PPMI entries 28,562

Processing period 1825-1849

348,888 tokens, vocabulary 2,162, PPMI entries 123,863

Processing period 1850-1874

359,510 tokens, vocabulary 2,222, PPMI entries 143,317

Processing period 1875-1899

397,727 tokens, vocabulary 2,479, PPMI entries 167,751

Processing period 1900-1924

367,619 tokens, vocabulary 2,326, PPMI entries 140,131

Processing period 1925-1949

241,117 tokens, vocabulary 1,648, PPMI entries 84,828

Processing period 1950-1974

445,987 tokens, vocabulary 2,449, PPMI entries 176,309

Processing period 1975-1999

464,612 tokens, vocabulary 2,467, PPMI entries 177,497

Processing period 2000-2024

524,747 tokens, vocabulary 2,657, PPMI entries 195,741

Processing period 2025-2049
1,903 tokens, vocabulary 6, PPMI entries 13
Skipping 2025-2049: too little text for 100 dimensions

# Semantic shift

In [5]:
from pathlib import Path


def load_and_sort_models(base_path="../models/lemmatized"):
    models = {}
    for period_path in Path(base_path).iterdir():
        if period_path.is_dir():
            period = period_path.name
            loaded_model = SVDAlgebra()
            loaded_model.load_model(period_path)
            models[period] = loaded_model

    # Sort by start year
    sorted_periods = sorted(models.keys(), key=lambda x: int(x.split("-")[0]))
    return {period: models[period] for period in sorted_periods}


models = load_and_sort_models()
print("Periods in chronological order:", list(models.keys()))

target_words = [
    "freedom",
    "democracy",
    "constitution",
    "justice",
    "government",
    "power",
    "law",
    "authority",
    "america",
    "union",
    "state",
    "nation",
]

Periods in chronological order: ['1775-1799', '1800-1824', '1825-1849', '1850-1874', '1875-1899', '1900-1924', '1925-1949', '1950-1974', '1975-1999', '2000-2024']

In [6]:
import math

import numpy as np

from chronowords.alignment.procrustes import ProcrustesAligner


def word_shift(aligner, word, emb1, emb2):
    """1 - aligned cosine similarity, or None if it is undefined.

    A vocabulary word with no PPMI entries has an all-zero embedding, for
    which get_word_similarity returns nan; those words are skipped.
    """
    with np.errstate(invalid="ignore"):  # zero vectors are handled below
        sim = aligner.get_word_similarity(word, emb1, emb2)
    if sim is None or not math.isfinite(sim):
        return None
    return 1 - sim


def analyze_shifts(models, target_words=None):
    """Analyze semantic shifts between consecutive periods."""
    periods = sorted(models.keys())
    results = {}

    for i in range(len(periods) - 1):
        period1, period2 = periods[i], periods[i + 1]
        model1, model2 = models[period1], models[period2]

        # Align embeddings
        aligner = ProcrustesAligner()
        metrics = aligner.fit(
            model1.embeddings,
            model2.embeddings,
            model1.vocabulary,
            model2.vocabulary,
        )

        print(f"\nAligned {period1} -> {period2}")
        print(f"Aligned words: {metrics.num_aligned_words}")
        print(f"Average similarity: {metrics.average_cosine_similarity:.3f}")

        # Analyze specific words
        if target_words:
            shifts = []
            for word in target_words:
                shift = word_shift(aligner, word, model1.embeddings, model2.embeddings)
                if shift is not None:
                    shifts.append((word, shift))

            # Sort by shift magnitude
            shifts.sort(key=lambda x: x[1], reverse=True)
            results[f"{period1}->{period2}"] = shifts

            print("\nTop shifted words:")
            for word, shift in shifts[:5]:
                print(f"{word}: {shift:.3f}")

    return results


# Analyze key political concepts
target_words = [
    "freedom",
    "democracy",
    "government",
    "power",
    "war",
    "peace",
    "america",
    "union",
    "state",
    "constitution",
    "rights",
    "justice",
    "law",
]

shifts = analyze_shifts(models, target_words)

Aligned 1775-1799 -> 1800-1824
Aligned words: 251
Average similarity: 0.604

Top shifted words:
law: 0.597
power: 0.508
justice: 0.449
peace: 0.419
constitution: 0.418

Aligned 1800-1824 -> 1825-1849
Aligned words: 686
Average similarity: 0.483

Top shifted words:
justice: 0.600
freedom: 0.587
america: 0.537
war: 0.521
peace: 0.507

Aligned 1825-1849 -> 1850-1874
Aligned words: 822
Average similarity: 0.538

Top shifted words:
justice: 0.494
union: 0.492
freedom: 0.490
america: 0.441
war: 0.356

Aligned 1850-1874 -> 1875-1899
Aligned words: 778
Average similarity: 0.539

Top shifted words:
freedom: 0.732
union: 0.586
america: 0.494
state: 0.466
constitution: 0.398

Aligned 1875-1899 -> 1900-1924
Aligned words: 783
Average similarity: 0.529

Top shifted words:
freedom: 0.822
union: 0.704
constitution: 0.528
justice: 0.475
state: 0.465

Aligned 1900-1924 -> 1925-1949
Aligned words: 778
Average similarity: 0.497

Top shifted words:
democracy: 0.789
union: 0.684
state: 0.546
power: 0.532
constitution: 0.532

Aligned 1925-1949 -> 1950-1974
Aligned words: 765
Average similarity: 0.505

Top shifted words:
democracy: 0.648
union: 0.624
freedom: 0.571
america: 0.540
power: 0.462

Aligned 1950-1974 -> 1975-1999
Aligned words: 807
Average similarity: 0.550

Top shifted words:
rights: 0.749
democracy: 0.644
power: 0.504
constitution: 0.493
freedom: 0.459

Aligned 1975-1999 -> 2000-2024
Aligned words: 801
Average similarity: 0.568

Top shifted words:
union: 0.678
rights: 0.671
constitution: 0.661
democracy: 0.477
power: 0.462

In [7]:
from pathlib import Path

import altair as alt
import pandas as pd


# Load preprocessed models
models = load_and_sort_models()
periods = sorted(models.keys(), key=lambda x: int(x.split("-")[0]))

shift_data = []
# For each period transition and its shifts
for i in range(len(periods) - 1):
    period1, period2 = periods[i], periods[i + 1]
    period_pair = f"{period1} → {period2}"

    # Get the shift data for this period transition
    model1, model2 = models[period1], models[period2]
    aligner = ProcrustesAligner()
    metrics = aligner.fit(
        model1.embeddings,
        model2.embeddings,
        model1.vocabulary,
        model2.vocabulary,
    )

    # Calculate shifts for target words
    for word in target_words:
        shift = word_shift(aligner, word, model1.embeddings, model2.embeddings)
        if shift is not None:
            shift_data.append(
                {
                    "period": period_pair,
                    "word": word,
                    "shift": shift,
                    "year": int(period1.split("-")[0]),
                }
            )

# Create DataFrame
df = pd.DataFrame(shift_data)

timeline = (
    alt.Chart(df)
    .mark_line(point=True)
    .encode(
        x=alt.X("year:Q", title="Year"),
        y=alt.Y("shift:Q", title="Semantic Change"),
        color="word:N",
        tooltip=["word", "year", "shift"],
    )
    .properties(width=800, height=400, title="Semantic Shifts Over Time")
    .interactive()
)

# Display the visualization
timeline

alt.Chart(...)

In [8]:
df

                    period          word     shift  year
0    1775-1799 → 1800-1824    government  0.414336  1775
1    1775-1799 → 1800-1824         power  0.508490  1775
2    1775-1799 → 1800-1824           war  0.398747  1775
3    1775-1799 → 1800-1824         peace  0.418933  1775
4    1775-1799 → 1800-1824         union  0.409895  1775
..                     ...           ...       ...   ...
98   1975-1999 → 2000-2024         state  0.335744  1975
99   1975-1999 → 2000-2024  constitution  0.660579  1975
100  1975-1999 → 2000-2024        rights  0.670989  1975
101  1975-1999 → 2000-2024       justice  0.393255  1975
102  1975-1999 → 2000-2024           law  0.214347  1975

[103 rows x 4 columns]

In [9]:
shift_data = []
# Use first period as reference
base_period = periods[0]
base_model = models[base_period]

for current_period in periods[1:]:
    current_model = models[current_period]
    aligner = ProcrustesAligner()
    metrics = aligner.fit(
        base_model.embeddings,
        current_model.embeddings,
        base_model.vocabulary,
        current_model.vocabulary,
    )

    for word in target_words:
        shift = word_shift(aligner, word, base_model.embeddings, current_model.embeddings)
        if shift is not None:
            shift_data.append(
                {"period": current_period, "word": word, "cumulative_shift": shift}
            )

df_cumulative = pd.DataFrame(shift_data)
df_cumulative["year"] = df_cumulative["period"].apply(lambda x: int(x.split("-")[0]))

cumulative_timeline = (
    alt.Chart(df_cumulative)
    .mark_line(point=True)
    .encode(
        x=alt.X("year:Q", title="Year"),
        y=alt.Y("cumulative_shift:Q", title="Cumulative Semantic Change from 1775"),
        color="word:N",
        tooltip=["word", "year", "cumulative_shift"],
    )
    .properties(
        width=800, height=400, title="Cumulative Semantic Shifts from First Period"
    )
    .interactive()
)

cumulative_timeline

alt.Chart(...)

In [10]:
df_cumulative

       period          word  cumulative_shift  year
0   1800-1824    government          0.414336  1800
1   1800-1824         power          0.508490  1800
2   1800-1824           war          0.398747  1800
3   1800-1824         peace          0.418933  1800
4   1800-1824         union          0.409895  1800
..        ...           ...               ...   ...
76  2000-2024         union          0.364932  2000
77  2000-2024         state          0.347284  2000
78  2000-2024  constitution          0.274573  2000
79  2000-2024       justice          0.365419  2000
80  2000-2024           law          0.381927  2000

[81 rows x 4 columns]

# Topic modeling with NMF

In [11]:
from chronowords.topics.nmf import TopicModel


def analyze_topics_by_period(models, n_topics=10):
    """Create topic models for each time period using existing PPMI matrices.

    Args:
        models: Dictionary of period -> model data from load_and_sort_models()
        n_topics: Number of topics to extract

    """
    topic_models = {}

    for period, model_data in models.items():
        print(f"\nAnalyzing topics for {period}")

        # The sparse PPMI matrix saved with each model (non-negative by
        # construction)
        vocabulary = model_data.vocabulary

        topic_model = TopicModel(n_topics=n_topics)
        topic_model.fit(model_data.ppmi, vocabulary)

        # Print topics
        print("\nTop topics:")
        topic_model.print_topics()

        topic_models[period] = topic_model

    return topic_models


# Create topic models using existing data
topic_models = analyze_topics_by_period(models)

Analyzing topics for 1775-1799

Top topics:

Topic 0:
  that: 0.0584
  not: 0.0527
  with: 0.0445
  the: 0.0418
  they: 0.0405
  have: 0.0359
  and: 0.0349
  from: 0.0308
  for: 0.0288
  our: 0.0271

Topic 1:
  you: 0.0867
  your: 0.0603
  consideration: 0.0388
  before: 0.0279
  will: 0.0272
  land: 0.0254
  the: 0.0232
  gentleman: 0.0217
  that: 0.0204
  for: 0.0197

Topic 2:
  representatives: 0.1511
  house: 0.1462
  senate: 0.1229
  the: 0.0496
  and: 0.0404
  direct: 0.0357
  citizen: 0.0310
  citizens: 0.0300
  treaty: 0.0291
  when: 0.0287

Topic 3:
  more: 0.0593
  can: 0.0462
  may: 0.0271
  must: 0.0270
  will: 0.0242
  have: 0.0241
  than: 0.0230
  not: 0.0216
  who: 0.0212
  which: 0.0150

Topic 4:
  government: 0.0746
  and: 0.0602
  country: 0.0527
  our: 0.0444
  nation: 0.0438
  interest: 0.0400
  its: 0.0386
  the: 0.0257
  which: 0.0255
  people: 0.0248

Topic 5:
  the: 0.0439
  for: 0.0431
  call: 0.0421
  measure: 0.0409
  defense: 0.0336
  within: 0.0321
  into: 0.0317
  service: 0.0292
  such: 0.0264
  may: 0.0255

Topic 6:
  united: 0.0871
  states: 0.0834
  the: 0.0445
  and: 0.0294
  say: 0.0245
  their: 0.0222
  foreign: 0.0217
  duty: 0.0213
  france: 0.0196
  law: 0.0182

Topic 7:
  recommend: 0.0590
  subject: 0.0584
  necessary: 0.0450
  your: 0.0410
  present: 0.0398
  myself: 0.0360
  that: 0.0338
  proper: 0.0331
  the: 0.0326
  president: 0.0316

Topic 8:
  session: 0.0755
  congress: 0.0559
  war: 0.0462
  between: 0.0429
  treaty: 0.0404
  the: 0.0360
  article: 0.0354
  last: 0.0306
  year: 0.0246
  present: 0.0242

Topic 9:
  than: 0.0421
  foreign: 0.0380
  right: 0.0348
  citizen: 0.0328
  public: 0.0320
  those: 0.0319
  own: 0.0302
  there: 0.0247
  law: 0.0229
  the: 0.0211

Analyzing topics for 1800-1824

Top topics:

Topic 0:
  the: 0.0571
  that: 0.0481
  and: 0.0450
  which: 0.0405
  with: 0.0354
  have: 0.0344
  they: 0.0330
  from: 0.0326
  their: 0.0305
  for: 0.0295

Topic 1:
  million: 0.0373
  treasury: 0.0318
  debt: 0.0266
  sum: 0.0215
  year: 0.0198
  during: 0.0194
  loan: 0.0189
  the: 0.0177
  public: 0.0176
  revenue: 0.0174

Topic 2:
  not: 0.0109
  any: 0.0088
  but: 0.0075
  effect: 0.0074
  might: 0.0070
  expect: 0.0066
  that: 0.0065
  have: 0.0062
  should: 0.0060
  without: 0.0058

Topic 3:
  united: 0.0350
  states: 0.0297
  between: 0.0269
  spain: 0.0224
  france: 0.0186
  government: 0.0183
  her: 0.0172
  with: 0.0163
  the: 0.0156
  two: 0.0148

Topic 4:
  and: 0.0207
  nation: 0.0193
  our: 0.0184
  citizen: 0.0166
  right: 0.0163
  every: 0.0156
  commerce: 0.0152
  interest: 0.0137
  country: 0.0129
  their: 0.0126

Topic 5:
  mississippi: 0.0464
  river: 0.0395
  territory: 0.0300
  water: 0.0290
  the: 0.0216
  and: 0.0199
  within: 0.0180
  limit: 0.0166
  ohio: 0.0160
  st.: 0.0145

Topic 6:
  you: 0.0620
  your: 0.0322
  will: 0.0167
  receive: 0.0156
  child: 0.0153
  see: 0.0149
  communicate: 0.0148
  before: 0.0145
  shall: 0.0137
  now: 0.0124

Topic 7:
  vessel: 0.0331
  force: 0.0248
  into: 0.0236
  ship: 0.0183
  port: 0.0174
  under: 0.0161
  coast: 0.0146
  war: 0.0139
  and: 0.0136
  mediterranean: 0.0128

Topic 8:
  last: 0.0491
  day: 0.0371
  year: 0.0356
  exceed: 0.0350
  september: 0.0331
  amount: 0.0302
  30th: 0.0289
  next: 0.0273
  estimate: 0.0239
  session: 0.0223

Topic 9:
  congress: 0.0328
  whether: 0.0221
  for: 0.0218
  the: 0.0199
  provision: 0.0184
  consideration: 0.0165
  attention: 0.0147
  subject: 0.0141
  this: 0.0128
  proper: 0.0127

Analyzing topics for 1825-1849

Top topics:

Topic 0:
  and: 0.0391
  the: 0.0374
  our: 0.0306
  which: 0.0227
  with: 0.0211
  their: 0.0208
  that: 0.0206
  have: 0.0201
  all: 0.0190
  they: 0.0165

Topic 1:
  your: 0.0220
  consideration: 0.0193
  attention: 0.0192
  congress: 0.0175
  subject: 0.0125
  you: 0.0104
  the: 0.0098
  upon: 0.0098
  that: 0.0097
  session: 0.0087

Topic 2:
  year: 0.0174
  amount: 0.0145
  million: 0.0130
  estimate: 0.0104
  expenditure: 0.0099
  treasury: 0.0097
  during: 0.0094
  the: 0.0094
  sum: 0.0090
  public: 0.0089

Topic 3:
  mexico: 0.0201
  united: 0.0176
  states: 0.0153
  her: 0.0135
  between: 0.0122
  treaty: 0.0120
  she: 0.0119
  with: 0.0111
  texas: 0.0110
  territory: 0.0109

Topic 4:
  can: 0.0032
  interest: 0.0029
  policy: 0.0028
  well: 0.0028
  result: 0.0027
  exist: 0.0026
  preserve: 0.0025
  doubt: 0.0025
  ever: 0.0025
  only: 0.0025

Topic 5:
  the: 0.0163
  power: 0.0162
  law: 0.0135
  constitution: 0.0127
  and: 0.0096
  its: 0.0092
  not: 0.0091
  they: 0.0090
  act: 0.0090
  government: 0.0089

Topic 6:
  river: 0.0269
  st.: 0.0249
  line: 0.0220
  lake: 0.0176
  north: 0.0170
  west: 0.0166
  parallel: 0.0150
  latitude: 0.0147
  boundary: 0.0140
  along: 0.0135

Topic 7:
  secretary: 0.0181
  report: 0.0163
  herewith: 0.0159
  message: 0.0148
  communicate: 0.0147
  minister: 0.0133
  transmit: 0.0128
  copy: 0.0124
  accompany: 0.0112
  his: 0.0109

Topic 8:
  last: 0.0361
  1846: 0.0245
  1848: 0.0220
  day: 0.0215
  1847: 0.0213
  march: 0.0195
  next: 0.0186
  1845: 0.0181
  july: 0.0181
  january: 0.0169

Topic 9:
  vessel: 0.0152
  port: 0.0112
  force: 0.0109
  duty: 0.0107
  military: 0.0095
  revenue: 0.0084
  and: 0.0079
  article: 0.0078
  service: 0.0078
  army: 0.0071

Analyzing topics for 1850-1874

Top topics:

Topic 0:
  the: 0.0335
  and: 0.0319
  that: 0.0249
  our: 0.0196
  they: 0.0180
  have: 0.0175
  which: 0.0175
  this: 0.0173
  with: 0.0172
  all: 0.0168

Topic 1:
  expenditure: 0.0178
  year: 0.0167
  amount: 0.0166
  during: 0.0161
  receipt: 0.0157
  fiscal: 0.0143
  acre: 0.0135
  estimate: 0.0116
  for: 0.0111
  increase: 0.0109

Topic 2:
  not: 0.0047
  slavery: 0.0047
  man: 0.0042
  they: 0.0041
  think: 0.0041
  you: 0.0041
  nebraska: 0.0040
  what: 0.0039
  slave: 0.0036
  that: 0.0036

Topic 3:
  mississippi: 0.0216
  carolina: 0.0215
  north: 0.0207
  texas: 0.0199
  louisiana: 0.0199
  virginia: 0.0194
  south: 0.0191
  florida: 0.0183
  arkansas: 0.0178
  alabama: 0.0150

Topic 4:
  last: 0.0214
  1861: 0.0168
  day: 0.0160
  1865: 0.0156
  1867: 0.0151
  1866: 0.0148
  march: 0.0144
  july: 0.0142
  september: 0.0140
  1857: 0.0136

Topic 5:
  report: 0.0126
  congress: 0.0115
  your: 0.0114
  secretary: 0.0111
  consideration: 0.0107
  attention: 0.0105
  subject: 0.0099
  the: 0.0098
  recommendation: 0.0094
  general: 0.0090

Topic 6:
  the: 0.0096
  law: 0.0084
  shall: 0.0082
  state: 0.0080
  person: 0.0079
  any: 0.0077
  constitution: 0.0075
  officer: 0.0072
  authority: 0.0070
  united: 0.0068

Topic 7:
  million: 0.0257
  year: 0.0210
  hundred: 0.0204
  three: 0.0185
  dollar: 0.0157
  thousand: 0.0148
  ago: 0.0146
  six: 0.0136
  sixty: 0.0113
  month: 0.0111

Topic 8:
  between: 0.0140
  and: 0.0111
  with: 0.0100
  the: 0.0096
  united: 0.0088
  states: 0.0079
  our: 0.0075
  nicaragua: 0.0071
  have: 0.0070
  american: 0.0069

Topic 9:
  currency: 0.0109
  value: 0.0099
  coin: 0.0094
  interest: 0.0094
  gold: 0.0086
  circulation: 0.0081
  payment: 0.0074
  debt: 0.0072
  specie: 0.0071
  silver: 0.0064

Analyzing topics for 1875-1899

Top topics:

Topic 0:
  the: 0.0336
  and: 0.0326
  our: 0.0204
  that: 0.0204
  their: 0.0189
  they: 0.0165
  this: 0.0164
  have: 0.0160
  which: 0.0153
  with: 0.0146

Topic 1:
  1891: 0.0128
  year: 0.0117
  amount: 0.0109
  expenditure: 0.0108
  estimate: 0.0107
  receipt: 0.0106
  over: 0.0105
  1892: 0.0103
  total: 0.0099
  last: 0.0097

Topic 2:
  congress: 0.0160
  attention: 0.0116
  the: 0.0106
  that: 0.0095
  report: 0.0085
  consideration: 0.0084
  recommendation: 0.0083
  your: 0.0080
  message: 0.0075
  secretary: 0.0072

Topic 3:
  between: 0.0125
  united: 0.0115
  states: 0.0101
  with: 0.0089
  treaty: 0.0084
  have: 0.0081
  the: 0.0079
  republic: 0.0073
  spain: 0.0073
  and: 0.0069

Topic 4:
  shall: 0.0122
  examination: 0.0114
  officer: 0.0094
  place: 0.0093
  classified: 0.0088
  person: 0.0087
  test: 0.0079
  service: 0.0077
  eligible: 0.0074
  who: 0.0071

Topic 5:
  vessel: 0.0108
  line: 0.0105
  port: 0.0099
  ship: 0.0092
  harbor: 0.0080
  and: 0.0076
  river: 0.0075
  coast: 0.0073
  pacific: 0.0070
  construction: 0.0065

Topic 6:
  silver: 0.0172
  gold: 0.0161
  coin: 0.0141
  note: 0.0129
  circulation: 0.0123
  bond: 0.0120
  issue: 0.0114
  treasury: 0.0112
  bullion: 0.0112
  dollar: 0.0105

Topic 7:
  can: 0.0034
  not: 0.0032
  should: 0.0031
  secure: 0.0030
  change: 0.0027
  legislation: 0.0027
  well: 0.0026
  result: 0.0025
  that: 0.0025
  method: 0.0025

Topic 8:
  million: 0.0170
  year: 0.0167
  one: 0.0158
  inch: 0.0154
  six: 0.0150
  hundred: 0.0148
  twenty: 0.0140
  day: 0.0136
  four: 0.0130
  thirty: 0.0127

Topic 9:
  product: 0.0165
  trade: 0.0121
  market: 0.0105
  our: 0.0096
  export: 0.0093
  foreign: 0.0093
  country: 0.0089
  industry: 0.0085
  increase: 0.0079
  commerce: 0.0072

Analyzing topics for 1900-1924

Top topics:

Topic 0:
  the: 0.0458
  and: 0.0389
  that: 0.0316
  our: 0.0252
  for: 0.0245
  have: 0.0238
  which: 0.0238
  this: 0.0224
  not: 0.0202
  with: 0.0187

Topic 1:
  congress: 0.0194
  report: 0.0110
  the: 0.0106
  secretary: 0.0100
  attention: 0.0097
  consideration: 0.0094
  session: 0.0091
  message: 0.0087
  your: 0.0083
  recommendation: 0.0082

Topic 2:
  year: 0.0229
  million: 0.0221
  hundred: 0.0206
  five: 0.0197
  four: 0.0192
  thousand: 0.0186
  dollar: 0.0180
  two: 0.0167
  three: 0.0164
  ago: 0.0145

Topic 3:
  receipt: 0.0156
  revenue: 0.0154
  amount: 0.0151
  increase: 0.0151
  estimate: 0.0139
  year: 0.0137
  expenditure: 0.0134
  total: 0.0129
  1911: 0.0120
  per: 0.0120

Topic 4:
  what: 0.0040
  they: 0.0038
  not: 0.0036
  but: 0.0034
  that: 0.0033
  more: 0.0032
  can: 0.0030
  peace: 0.0030
  never: 0.0029
  out: 0.0029

Topic 5:
  law: 0.0145
  interstate: 0.0123
  act: 0.0083
  combination: 0.0082
  such: 0.0081
  corporation: 0.0079
  federal: 0.0077
  any: 0.0074
  restraint: 0.0074
  the: 0.0073

Topic 6:
  country: 0.0119
  trade: 0.0102
  product: 0.0100
  our: 0.0094
  and: 0.0093
  industry: 0.0091
  foreign: 0.0089
  development: 0.0080
  business: 0.0073
  market: 0.0073

Topic 7:
  service: 0.0146
  officer: 0.0119
  department: 0.0106
  army: 0.0106
  navy: 0.0101
  and: 0.0085
  corps: 0.0085
  the: 0.0080
  should: 0.0075
  office: 0.0072

Topic 8:
  who: 0.0251
  man: 0.0245
  his: 0.0176
  wage: 0.0103
  their: 0.0101
  those: 0.0094
  and: 0.0084
  citizen: 0.0079
  employee: 0.0077
  worker: 0.0068

Topic 9:
  united: 0.0202
  states: 0.0172
  between: 0.0148
  panama: 0.0107
  with: 0.0104
  treaty: 0.0103
  government: 0.0103
  the: 0.0099
  republic: 0.0086
  convention: 0.0076

Analyzing topics for 1925-1949

Top topics:

Topic 0:
  the: 0.0536
  and: 0.0416
  that: 0.0346
  our: 0.0313
  have: 0.0293
  which: 0.0264
  with: 0.0262
  this: 0.0252
  they: 0.0240
  for: 0.0224

Topic 1:
  bank: 0.0134
  credit: 0.0119
  loan: 0.0113
  and: 0.0101
  agency: 0.0096
  industry: 0.0092
  through: 0.0091
  federal: 0.0089
  employment: 0.0085
  agriculture: 0.0080

Topic 2:
  year: 0.0367
  million: 0.0234
  billion: 0.0229
  ago: 0.0221
  dollar: 0.0219
  month: 0.0205
  hundred: 0.0154
  day: 0.0146
  half: 0.0126
  week: 0.0123

Topic 3:
  congress: 0.0178
  the: 0.0118
  legislation: 0.0105
  law: 0.0103
  should: 0.0094
  commission: 0.0089
  for: 0.0087
  authority: 0.0073
  under: 0.0073
  federal: 0.0072

Topic 4:
  you: 0.0102
  that: 0.0100
  what: 0.0076
  not: 0.0075
  say: 0.0074
  they: 0.0060
  have: 0.0054
  get: 0.0053
  this: 0.0051
  can: 0.0050

Topic 5:
  south: 0.0202
  africa: 0.0174
  germany: 0.0168
  and: 0.0151
  east: 0.0137
  the: 0.0132
  attack: 0.0125
  pacific: 0.0123
  from: 0.0122
  force: 0.0116

Topic 6:
  who: 0.0180
  man: 0.0180
  his: 0.0156
  freedom: 0.0131
  their: 0.0127
  and: 0.0124
  people: 0.0110
  liberty: 0.0098
  woman: 0.0092
  opportunity: 0.0090

Topic 7:
  peace: 0.0122
  economic: 0.0094
  security: 0.0086
  world: 0.0086
  nation: 0.0084
  progress: 0.0084
  our: 0.0080
  life: 0.0080
  problem: 0.0076
  system: 0.0071

Topic 8:
  price: 0.0194
  increase: 0.0149
  wage: 0.0136
  per: 0.0122
  than: 0.0114
  product: 0.0113
  cent: 0.0111
  commodity: 0.0111
  about: 0.0110
  rate: 0.0105

Topic 9:
  gun: 0.0406
  cruiser: 0.0325
  inch: 0.0310
  ton: 0.0283
  ship: 0.0282
  arm: 0.0219
  fleet: 0.0216
  submarine: 0.0195
  plane: 0.0177
  than: 0.0173

Analyzing topics for 1950-1974

Top topics:

Topic 0:
  the: 0.0469
  and: 0.0469
  our: 0.0300
  that: 0.0292
  for: 0.0256
  have: 0.0218
  this: 0.0215
  with: 0.0210
  which: 0.0207
  they: 0.0203

Topic 1:
  billion: 0.0239
  year: 0.0208
  million: 0.0183
  dollar: 0.0172
  percent: 0.0149
  month: 0.0107
  deficit: 0.0107
  per: 0.0103
  half: 0.0098
  budget: 0.0097

Topic 2:
  that: 0.0099
  you: 0.0098
  what: 0.0077
  say: 0.0071
  about: 0.0071
  think: 0.0062
  have: 0.0062
  not: 0.0053
  there: 0.0051
  would: 0.0050

Topic 3:
  mr.: 0.0209
  president: 0.0147
  general: 0.0122
  secretary: 0.0118
  member: 0.0107
  vice: 0.0106
  senator: 0.0106
  distinguished: 0.0099
  kennedy: 0.0095
  assistant: 0.0086

Topic 4:
  our: 0.0081
  freedom: 0.0080
  world: 0.0077
  peace: 0.0072
  free: 0.0066
  strength: 0.0060
  nation: 0.0058
  america: 0.0050
  common: 0.0048
  the: 0.0047

Topic 5:
  who: 0.0117
  man: 0.0099
  their: 0.0099
  every: 0.0097
  child: 0.0094
  his: 0.0094
  americans: 0.0089
  citizen: 0.0086
  life: 0.0082
  right: 0.0076

Topic 6:
  nuclear: 0.0202
  weapon: 0.0160
  test: 0.0107
  arm: 0.0096
  space: 0.0096
  agreement: 0.0087
  treaty: 0.0084
  outer: 0.0080
  power: 0.0079
  ban: 0.0078

Topic 7:
  south: 0.0175
  vietnam: 0.0160
  viet: 0.0141
  nam: 0.0127
  north: 0.0115
  force: 0.0113
  aggression: 0.0102
  attack: 0.0096
  communist: 0.0088
  korea: 0.0084

Topic 8:
  congress: 0.0138
  bill: 0.0119
  legislation: 0.0089
  act: 0.0087
  measure: 0.0081
  submit: 0.0074
  the: 0.0071
  law: 0.0068
  program: 0.0068
  budget: 0.0068

Topic 9:
  program: 0.0108
  development: 0.0082
  increase: 0.0071
  and: 0.0071
  price: 0.0066
  need: 0.0065
  federal: 0.0060
  tax: 0.0059
  income: 0.0058
  for: 0.0057

Analyzing topics for 1975-1999

Top topics:

Topic 0:
  the: 0.0490
  and: 0.0484
  that: 0.0333
  for: 0.0295
  our: 0.0284
  they: 0.0249
  have: 0.0248
  with: 0.0242
  this: 0.0231
  will: 0.0224

Topic 1:
  child: 0.0113
  school: 0.0103
  their: 0.0101
  who: 0.0097
  care: 0.0091
  health: 0.0085
  family: 0.0081
  and: 0.0072
  they: 0.0067
  education: 0.0064

Topic 2:
  tax: 0.0129
  increase: 0.0128
  percent: 0.0115
  rate: 0.0109
  cut: 0.0097
  inflation: 0.0096
  taxis: 0.0093
  spending: 0.0091
  billion: 0.0091
  income: 0.0086

Topic 3:
  which: 0.0099
  cooperation: 0.0090
  agreement: 0.0084
  issue: 0.0076
  between: 0.0069
  negotiation: 0.0067
  with: 0.0063
  the: 0.0059
  policy: 0.0058
  reform: 0.0058

Topic 4:
  that: 0.0085
  about: 0.0078
  you: 0.0076
  not: 0.0075
  say: 0.0074
  what: 0.0074
  think: 0.0073
  but: 0.0069
  know: 0.0062
  there: 0.0062

Topic 5:
  nuclear: 0.0293
  weapon: 0.0284
  missile: 0.0274
  soviet: 0.0135
  force: 0.0132
  strategic: 0.0130
  ballistic: 0.0123
  arm: 0.0118
  warhead: 0.0101
  range: 0.0099

Topic 6:
  year: 0.0231
  ago: 0.0178
  day: 0.0145
  million: 0.0114
  month: 0.0112
  week: 0.0092
  decade: 0.0081
  billion: 0.0080
  time: 0.0075
  half: 0.0075

Topic 7:
  europe: 0.0109
  united: 0.0096
  force: 0.0095
  east: 0.0090
  middle: 0.0083
  its: 0.0081
  israel: 0.0080
  states: 0.0075
  soviet: 0.0074
  lebanon: 0.0074

Topic 8:
  president: 0.0230
  mr.: 0.0208
  governor: 0.0172
  question: 0.0171
  you: 0.0152
  thank: 0.0136
  minute: 0.0125
  vice: 0.0123
  carter: 0.0122
  your: 0.0118

Topic 9:
  our: 0.0130
  peace: 0.0110
  freedom: 0.0109
  america: 0.0103
  world: 0.0098
  nation: 0.0088
  and: 0.0083
  future: 0.0076
  free: 0.0071
  democracy: 0.0068

Analyzing topics for 2000-2024

Top topics:

Topic 0:
  and: 0.0494
  the: 0.0462
  our: 0.0330
  that: 0.0301
  for: 0.0251
  with: 0.0219
  will: 0.0214
  this: 0.0210
  have: 0.0204
  they: 0.0188

Topic 1:
  you: 0.0116
  they: 0.0104
  say: 0.0103
  but: 0.0103
  not: 0.0097
  ’re: 0.0092
  that: 0.0091
  about: 0.0088
  what: 0.0083
  think: 0.0082

Topic 2:
  tax: 0.0118
  pay: 0.0088
  health: 0.0082
  for: 0.0080
  cost: 0.0078
  care: 0.0076
  cut: 0.0074
  income: 0.0072
  insurance: 0.0071
  taxis: 0.0071

Topic 3:
  afghanistan: 0.0137
  qaeda: 0.0133
  terrorist: 0.0131
  force: 0.0118
  iraq: 0.0112
  iraqi: 0.0078
  against: 0.0077
  troop: 0.0069
  kill: 0.0069
  military: 0.0068

Topic 4:
  freedom: 0.0083
  our: 0.0082
  peace: 0.0075
  nation: 0.0075
  must: 0.0071
  liberty: 0.0067
  human: 0.0061
  democracy: 0.0059
  the: 0.0057
  america: 0.0056

Topic 5:
  who: 0.0141
  child: 0.0107
  their: 0.0102
  she: 0.0097
  her: 0.0096
  family: 0.0075
  school: 0.0074
  home: 0.0073
  his: 0.0073
  life: 0.0073

Topic 6:
  thank: 0.0147
  president: 0.0144
  member: 0.0130
  congress: 0.0118
  mr.: 0.0104
  you: 0.0089
  fellow: 0.0087
  house: 0.0082
  vice: 0.0079
  general: 0.0078

Topic 7:
  year: 0.0203
  month: 0.0134
  ago: 0.0123
  week: 0.0114
  million: 0.0105
  day: 0.0095
  two: 0.0094
  decade: 0.0092
  three: 0.0078
  billion: 0.0074

Topic 8:
  energy: 0.0174
  clean: 0.0139
  technology: 0.0129
  new: 0.0110
  job: 0.0101
  research: 0.0091
  create: 0.0090
  and: 0.0086
  industry: 0.0077
  investment: 0.0070

Topic 9:
  weapon: 0.0229
  nuclear: 0.0190
  regime: 0.0158
  its: 0.0130
  iran: 0.0108
  destruction: 0.0101
  threaten: 0.0090
  mass: 0.0089
  missile: 0.0082
  attack: 0.0080

In [12]:
def process_topic_evolution(topic_models):
    """Process topic models into evolution chains for visualization.

    Args:
        topic_models: Dictionary mapping periods to TopicModel instances

    Returns:
        List of dicts containing evolution data for visualization

    """
    all_data = []
    # Sort periods chronologically
    periods = sorted(topic_models.keys(), key=lambda x: int(x.split("-")[0]))

    # Initialize chains from first period
    first_period = periods[0]
    first_model = topic_models[first_period]

    # Create initial topic chains
    chains = {}
    for idx, topic in enumerate(first_model.topics):
        chain_id = f"Chain_{idx}"
        top_words = [word for word, _ in topic.words[:3]]
        topic_label = ", ".join(top_words)

        chains[chain_id] = {
            "id": chain_id,
            "current_topic": topic,
            "label": topic_label,
        }

        # Add first period data point
        all_data.append(
            {
                "year": int(first_period.split("-")[0]),
                "period": first_period,
                "chain_id": chain_id,
                "topic_label": topic_label,
                "weight": topic.words[0][1],  # Use weight of top word
                "words": topic_label,
            }
        )

    # Follow alignments through subsequent periods
    for i in range(len(periods) - 1):
        period1, period2 = periods[i], periods[i + 1]
        model1 = topic_models[period1]
        model2 = topic_models[period2]

        # Get aligned topics
        aligned_topics = model1.align_with(model2)

        # Update chains based on alignments
        new_chains = {}
        used_target_topics = set()

        for aligned in aligned_topics:
            # Find chain containing source topic
            source_chain = None
            for chain_id, chain in chains.items():
                if chain["current_topic"].id == aligned.source_topic.id:
                    source_chain = chain
                    break

            if source_chain and aligned.target_topic.id not in used_target_topics:
                chain_id = source_chain["id"]
                top_words = [word for word, _ in aligned.target_topic.words[:3]]
                topic_label = ", ".join(top_words)

                # Add data point for this period
                all_data.append(
                    {
                        "year": int(period2.split("-")[0]),
                        "period": period2,
                        "chain_id": chain_id,
                        "topic_label": source_chain[
                            "label"
                        ],  # Keep original label for continuity
                        "weight": aligned.target_topic.words[0][1],
                        "words": topic_label,  # Current words for tooltip
                    }
                )

                # Update chain
                new_chains[chain_id] = {
                    "id": chain_id,
                    "current_topic": aligned.target_topic,
                    "label": source_chain["label"],
                }
                used_target_topics.add(aligned.target_topic.id)

        chains = new_chains

    return all_data


def plot_topic_trends(topic_models):
    """Create interactive visualization of topic evolution over time.

    Args:
        topic_models: Dictionary mapping periods to TopicModel instances

    Returns:
        altair.Chart: Interactive visualization

    """
    import altair as alt
    import pandas as pd

    # Process data
    all_data = process_topic_evolution(topic_models)
    df = pd.DataFrame(all_data)

    # Create base chart
    base = alt.Chart(df).encode(
        x=alt.X(
            "year:Q",
            title="Year",
            scale=alt.Scale(domain=[df.year.min(), df.year.max()]),
        ),
        color=alt.Color(
            "topic_label:N",
            legend=alt.Legend(title="Topics", orient="bottom", columns=2),
        ),
        tooltip=[
            alt.Tooltip("year:Q", title="Year"),
            alt.Tooltip("words:N", title="Top Words"),
            alt.Tooltip("weight:Q", title="Weight", format=".3f"),
        ],
    )

    # Create line chart with points
    lines = base.mark_line(size=2).encode(
        y=alt.Y("weight:Q", title="Topic Weight"), detail="chain_id:N"
    )

    points = base.mark_circle(size=60).encode(y=alt.Y("weight:Q", title="Topic Weight"))

    # Combine charts
    chart = (
        (lines + points)
        .properties(width=800, height=400, title="Topic Evolution Over Time")
        .interactive()
    )

    # Add selection
    topic_selection = alt.selection_point(fields=["topic_label"], bind="legend")

    chart = chart.add_params(topic_selection).encode(
        opacity=alt.condition(topic_selection, alt.value(1), alt.value(0.2))
    )

    return chart


# Example usage:
topic_models = analyze_topics_by_period(models)
chart = plot_topic_trends(topic_models)
chart
# chart.save('topic_evolution.html')  # Save interactive chart

Analyzing topics for 1775-1799

Top topics:

Topic 0:
  that: 0.0584
  not: 0.0527
  with: 0.0445
  the: 0.0418
  they: 0.0405
  have: 0.0359
  and: 0.0349
  from: 0.0308
  for: 0.0288
  our: 0.0271

Topic 1:
  you: 0.0867
  your: 0.0603
  consideration: 0.0388
  before: 0.0279
  will: 0.0272
  land: 0.0254
  the: 0.0232
  gentleman: 0.0217
  that: 0.0204
  for: 0.0197

Topic 2:
  representatives: 0.1511
  house: 0.1462
  senate: 0.1229
  the: 0.0496
  and: 0.0404
  direct: 0.0357
  citizen: 0.0310
  citizens: 0.0300
  treaty: 0.0291
  when: 0.0287

Topic 3:
  more: 0.0593
  can: 0.0462
  may: 0.0271
  must: 0.0270
  will: 0.0242
  have: 0.0241
  than: 0.0230
  not: 0.0216
  who: 0.0212
  which: 0.0150

Topic 4:
  government: 0.0746
  and: 0.0602
  country: 0.0527
  our: 0.0444
  nation: 0.0438
  interest: 0.0400
  its: 0.0386
  the: 0.0257
  which: 0.0255
  people: 0.0248

Topic 5:
  the: 0.0439
  for: 0.0431
  call: 0.0421
  measure: 0.0409
  defense: 0.0336
  within: 0.0321
  into: 0.0317
  service: 0.0292
  such: 0.0264
  may: 0.0255

Topic 6:
  united: 0.0871
  states: 0.0834
  the: 0.0445
  and: 0.0294
  say: 0.0245
  their: 0.0222
  foreign: 0.0217
  duty: 0.0213
  france: 0.0196
  law: 0.0182

Topic 7:
  recommend: 0.0590
  subject: 0.0584
  necessary: 0.0450
  your: 0.0410
  present: 0.0398
  myself: 0.0360
  that: 0.0338
  proper: 0.0331
  the: 0.0326
  president: 0.0316

Topic 8:
  session: 0.0755
  congress: 0.0559
  war: 0.0462
  between: 0.0429
  treaty: 0.0404
  the: 0.0360
  article: 0.0354
  last: 0.0306
  year: 0.0246
  present: 0.0242

Topic 9:
  than: 0.0421
  foreign: 0.0380
  right: 0.0348
  citizen: 0.0328
  public: 0.0320
  those: 0.0319
  own: 0.0302
  there: 0.0247
  law: 0.0229
  the: 0.0211

Analyzing topics for 1800-1824

Top topics:

Topic 0:
  the: 0.0575
  that: 0.0491
  and: 0.0457
  which: 0.0402
  with: 0.0360
  have: 0.0350
  they: 0.0333
  from: 0.0316
  their: 0.0310
  for: 0.0305

Topic 1:
  million: 0.0325
  year: 0.0295
  amount: 0.0258
  treasury: 0.0237
  sum: 0.0211
  exceed: 0.0203
  last: 0.0188
  during: 0.0179
  the: 0.0170
  estimate: 0.0163

Topic 2:
  not: 0.0106
  any: 0.0090
  effect: 0.0075
  but: 0.0074
  might: 0.0068
  that: 0.0067
  expect: 0.0066
  have: 0.0060
  should: 0.0059
  without: 0.0058

Topic 3:
  united: 0.0349
  states: 0.0296
  between: 0.0277
  spain: 0.0225
  france: 0.0186
  government: 0.0179
  her: 0.0173
  with: 0.0171
  two: 0.0151
  the: 0.0149

Topic 4:
  and: 0.0203
  our: 0.0182
  nation: 0.0175
  citizen: 0.0168
  right: 0.0164
  every: 0.0158
  interest: 0.0151
  commerce: 0.0146
  country: 0.0124
  their: 0.0121

Topic 5:
  mississippi: 0.0471
  river: 0.0401
  territory: 0.0305
  water: 0.0292
  the: 0.0218
  and: 0.0196
  within: 0.0181
  limit: 0.0168
  ohio: 0.0163
  st.: 0.0147

Topic 6:
  you: 0.0558
  your: 0.0449
  child: 0.0218
  see: 0.0204
  land: 0.0154
  will: 0.0142
  they: 0.0141
  say: 0.0140
  what: 0.0132
  shall: 0.0130

Topic 7:
  vessel: 0.0329
  force: 0.0252
  into: 0.0243
  ship: 0.0180
  port: 0.0177
  under: 0.0161
  coast: 0.0147
  and: 0.0137
  for: 0.0133
  mediterranean: 0.0131

Topic 8:
  communicate: 0.0291
  you: 0.0256
  before: 0.0232
  receive: 0.0231
  soon: 0.0213
  lay: 0.0209
  secretary: 0.0201
  transmit: 0.0193
  state: 0.0184
  the: 0.0168

Topic 9:
  congress: 0.0347
  whether: 0.0239
  for: 0.0224
  the: 0.0202
  provision: 0.0197
  consideration: 0.0172
  attention: 0.0159
  session: 0.0149
  act: 0.0130
  may: 0.0124

Analyzing topics for 1825-1849

Top topics:

Topic 0:
  and: 0.0391
  the: 0.0374
  our: 0.0306
  which: 0.0227
  with: 0.0211
  their: 0.0208
  that: 0.0206
  have: 0.0201
  all: 0.0190
  they: 0.0165

Topic 1:
  your: 0.0220
  consideration: 0.0193
  attention: 0.0192
  congress: 0.0175
  subject: 0.0125
  you: 0.0104
  the: 0.0098
  upon: 0.0098
  that: 0.0097
  session: 0.0087

Topic 2:
  year: 0.0174
  amount: 0.0145
  million: 0.0130
  estimate: 0.0104
  expenditure: 0.0099
  treasury: 0.0097
  during: 0.0094
  the: 0.0094
  sum: 0.0090
  public: 0.0089

Topic 3:
  mexico: 0.0201
  united: 0.0176
  states: 0.0153
  her: 0.0135
  between: 0.0122
  treaty: 0.0120
  she: 0.0119
  with: 0.0111
  texas: 0.0110
  territory: 0.0109

Topic 4:
  can: 0.0032
  interest: 0.0029
  policy: 0.0028
  well: 0.0028
  result: 0.0027
  exist: 0.0026
  preserve: 0.0025
  doubt: 0.0025
  ever: 0.0025
  only: 0.0025

Topic 5:
  the: 0.0163
  power: 0.0162
  law: 0.0135
  constitution: 0.0127
  and: 0.0096
  its: 0.0092
  not: 0.0091
  they: 0.0090
  act: 0.0090
  government: 0.0089

Topic 6:
  river: 0.0269
  st.: 0.0249
  line: 0.0220
  lake: 0.0176
  north: 0.0170
  west: 0.0166
  parallel: 0.0150
  latitude: 0.0147
  boundary: 0.0140
  along: 0.0135

Topic 7:
  secretary: 0.0181
  report: 0.0163
  herewith: 0.0159
  message: 0.0148
  communicate: 0.0147
  minister: 0.0133
  transmit: 0.0128
  copy: 0.0124
  accompany: 0.0112
  his: 0.0109

Topic 8:
  last: 0.0361
  1846: 0.0245
  1848: 0.0220
  day: 0.0215
  1847: 0.0213
  march: 0.0195
  next: 0.0186
  1845: 0.0181
  july: 0.0181
  january: 0.0169

Topic 9:
  vessel: 0.0152
  port: 0.0112
  force: 0.0109
  duty: 0.0107
  military: 0.0095
  revenue: 0.0084
  and: 0.0079
  article: 0.0078
  service: 0.0078
  army: 0.0071

Analyzing topics for 1850-1874

Top topics:

Topic 0:
  the: 0.0335
  and: 0.0319
  that: 0.0248
  our: 0.0196
  they: 0.0180
  have: 0.0175
  which: 0.0175
  this: 0.0173
  with: 0.0172
  all: 0.0168

Topic 1:
  expenditure: 0.0178
  year: 0.0167
  amount: 0.0166
  during: 0.0161
  receipt: 0.0157
  fiscal: 0.0143
  acre: 0.0135
  estimate: 0.0116
  for: 0.0111
  increase: 0.0109

Topic 2:
  not: 0.0047
  slavery: 0.0047
  man: 0.0042
  they: 0.0041
  think: 0.0041
  you: 0.0041
  nebraska: 0.0040
  what: 0.0039
  slave: 0.0036
  that: 0.0036

Topic 3:
  mississippi: 0.0216
  carolina: 0.0216
  north: 0.0207
  louisiana: 0.0200
  texas: 0.0199
  virginia: 0.0194
  south: 0.0191
  florida: 0.0184
  arkansas: 0.0179
  alabama: 0.0150

Topic 4:
  last: 0.0214
  1861: 0.0168
  day: 0.0160
  1865: 0.0156
  1867: 0.0151
  1866: 0.0148
  march: 0.0144
  july: 0.0142
  september: 0.0140
  1857: 0.0136

Topic 5:
  report: 0.0126
  congress: 0.0115
  your: 0.0114
  secretary: 0.0111
  consideration: 0.0107
  attention: 0.0105
  subject: 0.0099
  the: 0.0098
  recommendation: 0.0094
  general: 0.0090

Topic 6:
  the: 0.0096
  law: 0.0084
  shall: 0.0082
  state: 0.0080
  person: 0.0079
  any: 0.0077
  constitution: 0.0075
  officer: 0.0072
  authority: 0.0070
  united: 0.0068

Topic 7:
  million: 0.0257
  year: 0.0210
  hundred: 0.0204
  three: 0.0185
  dollar: 0.0157
  thousand: 0.0147
  ago: 0.0146
  six: 0.0136
  sixty: 0.0113
  month: 0.0111

Topic 8:
  between: 0.0140
  and: 0.0111
  with: 0.0100
  the: 0.0096
  united: 0.0088
  states: 0.0079
  our: 0.0075
  nicaragua: 0.0071
  have: 0.0070
  american: 0.0069

Topic 9:
  currency: 0.0109
  value: 0.0099
  coin: 0.0094
  interest: 0.0093
  gold: 0.0086
  circulation: 0.0080
  payment: 0.0074
  debt: 0.0072
  specie: 0.0071
  silver: 0.0064

Analyzing topics for 1875-1899

Top topics:

Topic 0:
  the: 0.0336
  and: 0.0326
  our: 0.0204
  that: 0.0204
  their: 0.0189
  they: 0.0165
  this: 0.0164
  have: 0.0160
  which: 0.0153
  with: 0.0146

Topic 1:
  1891: 0.0128
  year: 0.0117
  amount: 0.0109
  expenditure: 0.0108
  estimate: 0.0107
  receipt: 0.0106
  over: 0.0105
  1892: 0.0103
  total: 0.0099
  last: 0.0097

Topic 2:
  congress: 0.0160
  attention: 0.0116
  the: 0.0106
  that: 0.0095
  report: 0.0085
  consideration: 0.0084
  recommendation: 0.0083
  your: 0.0080
  message: 0.0075
  secretary: 0.0072

Topic 3:
  between: 0.0125
  united: 0.0115
  states: 0.0101
  with: 0.0089
  treaty: 0.0084
  have: 0.0081
  the: 0.0079
  republic: 0.0073
  spain: 0.0073
  and: 0.0069

Topic 4:
  shall: 0.0122
  examination: 0.0114
  officer: 0.0094
  place: 0.0093
  classified: 0.0088
  person: 0.0087
  test: 0.0079
  service: 0.0077
  eligible: 0.0074
  who: 0.0071

Topic 5:
  vessel: 0.0108
  line: 0.0105
  port: 0.0099
  ship: 0.0092
  harbor: 0.0080
  and: 0.0076
  river: 0.0075
  coast: 0.0073
  pacific: 0.0070
  construction: 0.0065

Topic 6:
  silver: 0.0172
  gold: 0.0161
  coin: 0.0141
  note: 0.0129
  circulation: 0.0123
  bond: 0.0120
  issue: 0.0114
  treasury: 0.0112
  bullion: 0.0112
  dollar: 0.0105

Topic 7:
  can: 0.0034
  not: 0.0032
  should: 0.0031
  secure: 0.0030
  change: 0.0027
  legislation: 0.0027
  well: 0.0026
  result: 0.0025
  that: 0.0025
  method: 0.0025

Topic 8:
  million: 0.0170
  year: 0.0167
  one: 0.0158
  inch: 0.0154
  six: 0.0150
  hundred: 0.0148
  twenty: 0.0140
  day: 0.0136
  four: 0.0130
  thirty: 0.0127

Topic 9:
  product: 0.0165
  trade: 0.0121
  market: 0.0105
  our: 0.0096
  export: 0.0093
  foreign: 0.0093
  country: 0.0089
  industry: 0.0085
  increase: 0.0079
  commerce: 0.0072

Analyzing topics for 1900-1924

Top topics:

Topic 0:
  the: 0.0458
  and: 0.0389
  that: 0.0316
  our: 0.0252
  for: 0.0245
  have: 0.0238
  which: 0.0238
  this: 0.0224
  not: 0.0202
  with: 0.0187

Topic 1:
  congress: 0.0194
  report: 0.0110
  the: 0.0106
  secretary: 0.0100
  attention: 0.0097
  consideration: 0.0094
  session: 0.0091
  message: 0.0087
  your: 0.0083
  recommendation: 0.0082

Topic 2:
  year: 0.0229
  million: 0.0221
  hundred: 0.0206
  five: 0.0197
  four: 0.0192
  thousand: 0.0186
  dollar: 0.0180
  two: 0.0167
  three: 0.0164
  ago: 0.0145

Topic 3:
  receipt: 0.0156
  revenue: 0.0154
  amount: 0.0151
  increase: 0.0151
  estimate: 0.0139
  year: 0.0137
  expenditure: 0.0134
  total: 0.0129
  1911: 0.0120
  per: 0.0120

Topic 4:
  what: 0.0040
  they: 0.0038
  not: 0.0036
  but: 0.0034
  that: 0.0033
  more: 0.0032
  can: 0.0030
  peace: 0.0030
  never: 0.0029
  out: 0.0029

Topic 5:
  law: 0.0145
  interstate: 0.0123
  act: 0.0083
  combination: 0.0082
  such: 0.0081
  corporation: 0.0079
  federal: 0.0077
  any: 0.0074
  restraint: 0.0074
  the: 0.0073

Topic 6:
  country: 0.0119
  trade: 0.0102
  product: 0.0100
  our: 0.0094
  and: 0.0093
  industry: 0.0091
  foreign: 0.0089
  development: 0.0080
  business: 0.0073
  market: 0.0073

Topic 7:
  service: 0.0146
  officer: 0.0119
  department: 0.0106
  army: 0.0106
  navy: 0.0101
  and: 0.0085
  corps: 0.0085
  the: 0.0080
  should: 0.0075
  office: 0.0072

Topic 8:
  who: 0.0251
  man: 0.0245
  his: 0.0176
  wage: 0.0103
  their: 0.0101
  those: 0.0094
  and: 0.0084
  citizen: 0.0079
  employee: 0.0077
  worker: 0.0068

Topic 9:
  united: 0.0202
  states: 0.0172
  between: 0.0148
  panama: 0.0107
  with: 0.0104
  treaty: 0.0103
  government: 0.0103
  the: 0.0099
  republic: 0.0086
  convention: 0.0076

Analyzing topics for 1925-1949

Top topics:

Topic 0:
  the: 0.0536
  and: 0.0416
  that: 0.0346
  our: 0.0313
  have: 0.0293
  which: 0.0264
  with: 0.0262
  this: 0.0252
  they: 0.0240
  for: 0.0224

Topic 1:
  bank: 0.0134
  credit: 0.0119
  loan: 0.0113
  and: 0.0101
  agency: 0.0096
  industry: 0.0092
  through: 0.0091
  federal: 0.0089
  employment: 0.0085
  agriculture: 0.0080

Topic 2:
  year: 0.0367
  million: 0.0234
  billion: 0.0229
  ago: 0.0221
  dollar: 0.0219
  month: 0.0205
  hundred: 0.0154
  day: 0.0146
  half: 0.0126
  week: 0.0123

Topic 3:
  congress: 0.0178
  the: 0.0118
  legislation: 0.0105
  law: 0.0103
  should: 0.0094
  commission: 0.0089
  for: 0.0087
  authority: 0.0073
  under: 0.0073
  federal: 0.0072

Topic 4:
  you: 0.0102
  that: 0.0100
  what: 0.0076
  not: 0.0075
  say: 0.0074
  they: 0.0060
  have: 0.0054
  get: 0.0053
  this: 0.0051
  can: 0.0050

Topic 5:
  south: 0.0202
  africa: 0.0174
  germany: 0.0168
  and: 0.0151
  east: 0.0137
  the: 0.0132
  attack: 0.0125
  pacific: 0.0123
  from: 0.0122
  force: 0.0116

Topic 6:
  who: 0.0180
  man: 0.0180
  his: 0.0156
  freedom: 0.0131
  their: 0.0127
  and: 0.0124
  people: 0.0110
  liberty: 0.0098
  woman: 0.0092
  opportunity: 0.0090

Topic 7:
  peace: 0.0122
  economic: 0.0094
  security: 0.0086
  world: 0.0086
  nation: 0.0084
  progress: 0.0084
  our: 0.0080
  life: 0.0080
  problem: 0.0076
  system: 0.0071

Topic 8:
  price: 0.0194
  increase: 0.0149
  wage: 0.0136
  per: 0.0122
  than: 0.0114
  product: 0.0113
  cent: 0.0111
  commodity: 0.0111
  about: 0.0110
  rate: 0.0105

Topic 9:
  gun: 0.0406
  cruiser: 0.0325
  inch: 0.0310
  ton: 0.0283
  ship: 0.0282
  arm: 0.0219
  fleet: 0.0216
  submarine: 0.0195
  plane: 0.0177
  than: 0.0173

Analyzing topics for 1950-1974

Top topics:

Topic 0:
  the: 0.0469
  and: 0.0469
  our: 0.0300
  that: 0.0292
  for: 0.0256
  have: 0.0218
  this: 0.0215
  with: 0.0210
  which: 0.0207
  they: 0.0203

Topic 1:
  billion: 0.0239
  year: 0.0208
  million: 0.0183
  dollar: 0.0172
  percent: 0.0149
  month: 0.0107
  deficit: 0.0107
  per: 0.0103
  half: 0.0098
  budget: 0.0097

Topic 2:
  that: 0.0099
  you: 0.0098
  what: 0.0077
  say: 0.0071
  about: 0.0071
  think: 0.0062
  have: 0.0062
  not: 0.0053
  there: 0.0051
  would: 0.0050

Topic 3:
  program: 0.0109
  development: 0.0082
  increase: 0.0071
  and: 0.0071
  price: 0.0065
  need: 0.0065
  federal: 0.0060
  tax: 0.0059
  income: 0.0058
  for: 0.0057

Topic 4:
  our: 0.0081
  freedom: 0.0080
  world: 0.0077
  peace: 0.0072
  free: 0.0066
  strength: 0.0060
  nation: 0.0058
  america: 0.0050
  common: 0.0048
  the: 0.0047

Topic 5:
  who: 0.0117
  man: 0.0099
  their: 0.0099
  every: 0.0097
  child: 0.0094
  his: 0.0094
  americans: 0.0089
  citizen: 0.0086
  life: 0.0082
  right: 0.0076

Topic 6:
  mr.: 0.0209
  president: 0.0147
  general: 0.0122
  secretary: 0.0118
  member: 0.0107
  vice: 0.0106
  senator: 0.0106
  distinguished: 0.0099
  kennedy: 0.0095
  assistant: 0.0086

Topic 7:
  south: 0.0175
  vietnam: 0.0160
  viet: 0.0141
  nam: 0.0127
  north: 0.0115
  force: 0.0113
  aggression: 0.0102
  attack: 0.0096
  communist: 0.0088
  korea: 0.0084

Topic 8:
  congress: 0.0138
  bill: 0.0119
  legislation: 0.0089
  act: 0.0087
  measure: 0.0081
  submit: 0.0074
  the: 0.0071
  law: 0.0068
  budget: 0.0068
  program: 0.0067

Topic 9:
  nuclear: 0.0202
  weapon: 0.0160
  test: 0.0107
  arm: 0.0096
  space: 0.0096
  agreement: 0.0087
  treaty: 0.0084
  outer: 0.0080
  power: 0.0079
  ban: 0.0078

Analyzing topics for 1975-1999

Top topics:

Topic 0:
  the: 0.0490
  and: 0.0484
  that: 0.0333
  for: 0.0295
  our: 0.0284
  they: 0.0249
  have: 0.0248
  with: 0.0242
  this: 0.0231
  will: 0.0224

Topic 1:
  child: 0.0113
  school: 0.0103
  their: 0.0101
  who: 0.0097
  care: 0.0091
  health: 0.0085
  family: 0.0081
  and: 0.0072
  they: 0.0067
  education: 0.0064

Topic 2:
  tax: 0.0129
  increase: 0.0128
  percent: 0.0115
  rate: 0.0109
  cut: 0.0097
  inflation: 0.0096
  taxis: 0.0093
  spending: 0.0091
  billion: 0.0091
  income: 0.0086

Topic 3:
  which: 0.0099
  cooperation: 0.0090
  agreement: 0.0084
  issue: 0.0076
  between: 0.0069
  negotiation: 0.0067
  with: 0.0063
  the: 0.0059
  policy: 0.0058
  reform: 0.0058

Topic 4:
  that: 0.0085
  about: 0.0078
  you: 0.0076
  not: 0.0075
  say: 0.0074
  what: 0.0074
  think: 0.0073
  but: 0.0069
  know: 0.0062
  there: 0.0062

Topic 5:
  nuclear: 0.0293
  weapon: 0.0284
  missile: 0.0274
  soviet: 0.0135
  force: 0.0132
  strategic: 0.0130
  ballistic: 0.0123
  arm: 0.0118
  warhead: 0.0101
  range: 0.0099

Topic 6:
  year: 0.0231
  ago: 0.0178
  day: 0.0145
  million: 0.0114
  month: 0.0112
  week: 0.0092
  decade: 0.0081
  billion: 0.0080
  time: 0.0075
  half: 0.0075

Topic 7:
  europe: 0.0109
  united: 0.0096
  force: 0.0095
  east: 0.0090
  middle: 0.0083
  its: 0.0081
  israel: 0.0080
  states: 0.0075
  soviet: 0.0074
  lebanon: 0.0074

Topic 8:
  president: 0.0230
  mr.: 0.0208
  governor: 0.0172
  question: 0.0171
  you: 0.0152
  thank: 0.0136
  minute: 0.0125
  vice: 0.0123
  carter: 0.0122
  your: 0.0118

Topic 9:
  our: 0.0130
  peace: 0.0110
  freedom: 0.0109
  america: 0.0103
  world: 0.0098
  nation: 0.0088
  and: 0.0083
  future: 0.0076
  free: 0.0071
  democracy: 0.0068

Analyzing topics for 2000-2024

Top topics:

Topic 0:
  and: 0.0494
  the: 0.0462
  our: 0.0330
  that: 0.0301
  for: 0.0251
  with: 0.0219
  will: 0.0214
  this: 0.0210
  have: 0.0204
  they: 0.0188

Topic 1:
  you: 0.0116
  they: 0.0104
  say: 0.0103
  but: 0.0103
  not: 0.0097
  ’re: 0.0092
  that: 0.0091
  about: 0.0088
  what: 0.0083
  think: 0.0082

Topic 2:
  tax: 0.0118
  pay: 0.0088
  health: 0.0082
  for: 0.0080
  cost: 0.0078
  care: 0.0076
  cut: 0.0074
  income: 0.0072
  insurance: 0.0071
  taxis: 0.0071

Topic 3:
  afghanistan: 0.0137
  qaeda: 0.0133
  terrorist: 0.0131
  force: 0.0118
  iraq: 0.0112
  iraqi: 0.0078
  against: 0.0077
  troop: 0.0069
  kill: 0.0069
  military: 0.0068

Topic 4:
  freedom: 0.0083
  our: 0.0082
  peace: 0.0075
  nation: 0.0075
  must: 0.0071
  liberty: 0.0067
  human: 0.0061
  democracy: 0.0059
  the: 0.0057
  america: 0.0056

Topic 5:
  who: 0.0141
  child: 0.0107
  their: 0.0102
  she: 0.0097
  her: 0.0096
  family: 0.0075
  school: 0.0074
  home: 0.0073
  his: 0.0073
  life: 0.0073

Topic 6:
  thank: 0.0147
  president: 0.0144
  member: 0.0130
  congress: 0.0118
  mr.: 0.0104
  you: 0.0089
  fellow: 0.0087
  house: 0.0082
  vice: 0.0079
  general: 0.0078

Topic 7:
  year: 0.0203
  month: 0.0134
  ago: 0.0123
  week: 0.0114
  million: 0.0105
  day: 0.0095
  two: 0.0094
  decade: 0.0092
  three: 0.0078
  billion: 0.0074

Topic 8:
  energy: 0.0174
  clean: 0.0139
  technology: 0.0129
  new: 0.0110
  job: 0.0101
  research: 0.0091
  create: 0.0090
  and: 0.0086
  industry: 0.0077
  investment: 0.0070

Topic 9:
  weapon: 0.0229
  nuclear: 0.0190
  regime: 0.0158
  its: 0.0130
  iran: 0.0108
  destruction: 0.0101
  threaten: 0.0090
  mass: 0.0089
  missile: 0.0082
  attack: 0.0080

alt.LayerChart(...)